<?php
/**
 * Title: FAQ
 * Slug: faq
 * Theme: goafrica-ollie-child
 * Inserter: yes
 */
?>


<!-- wp:group {"metadata":{"name":"FAQ"},"align":"full","className":"is-style-ga-page-section-default","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"blockGap":"var:preset|spacing|large"}},"backgroundColor":"primary-light","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull is-style-ga-page-section-default has-primary-light-background-color has-background" style="margin-top:0;margin-bottom:0"><!-- wp:group {"metadata":{"name":"Header"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"blockGap":"var:preset|spacing|small"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:paragraph {"className":"has-text-align-center is-style-ga-uppercase-bold has-primary-alt-accent-color has-text-color has-link-color","style":{"typography":{"textAlign":"center","fontStyle":"normal","fontWeight":"500"},"elements":{"link":{"color":{"text":"var:preset|color|primary-alt-accent"}}}},"textColor":"primary-alt-accent"} -->
<p class="has-text-align-center is-style-ga-uppercase-bold has-primary-alt-accent-color has-text-color has-link-color" style="font-style:normal;font-weight:500">FAQ</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"has-text-align-center","style":{"typography":{"textAlign":"center"},"elements":{"link":{"color":{"text":"var:preset|color|primary"}}}},"textColor":"primary"} -->
<h2 class="wp-block-heading has-text-align-center has-primary-color has-text-color has-link-color">Veelgestelde vragen</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:yoast/faq-block {"questions":[{"id":"faq-question-1776770203629","question":"Hoe werkt het aanvragen van een offerte?","answer":"Het aanvragen van een offerte is geheel vrijblijvend. Vul het formulier in op onze website of neem telefonisch contact op. Wij nemen binnen 1 werkdag contact met u op om uw wensen te bespreken.","jsonQuestion":"Hoe werkt het aanvragen van een offerte?","jsonAnswer":"Het aanvragen van een offerte is geheel vrijblijvend. Vul het formulier in op onze website of neem telefonisch contact op. Wij nemen binnen 1 werkdag contact met u op om uw wensen te bespreken.","images":[]},{"id":"faq-question-1776770229866","question":"Is een reis bij GoAfrica altijd maatwerk?","answer":"Ja, wij zijn gespecialiseerd in maatwerk. Hoewel we voorbeeldreizen tonen ter inspiratie, passen we elke reis aan op uw specifieke wensen, budget en reisgezelschap.","jsonQuestion":"Is een reis bij GoAfrica altijd maatwerk?","jsonAnswer":"Ja, wij zijn gespecialiseerd in maatwerk. Hoewel we voorbeeldreizen tonen ter inspiratie, passen we elke reis aan op uw specifieke wensen, budget en reisgezelschap.","images":[]},{"id":"faq-question-1776770249073","question":"Wat is de beste reistijd voor Afrika?","answer":"Dit verschilt per land en regio. Over het algemeen is Afrika het hele jaar door te bezoeken. Oost-Afrika heeft twee regenseizoenen, terwijl Zuidelijk Afrika seizoenen heeft die tegengesteld zijn aan die van Europa. Wij adviseren u graag per bestemming.","jsonQuestion":"Wat is de beste reistijd voor Afrika?","jsonAnswer":"Dit verschilt per land en regio. Over het algemeen is Afrika het hele jaar door te bezoeken. Oost-Afrika heeft twee regenseizoenen, terwijl Zuidelijk Afrika seizoenen heeft die tegengesteld zijn aan die van Europa. Wij adviseren u graag per bestemming.","images":[]},{"id":"faq-question-1776770261645","question":"Zijn jullie reizen geschikt voor gezinnen?","answer":"Absoluut! Wij hebben veel ervaring met het organiseren van familiereizen. We selecteren kindvriendelijke accommodaties en activiteiten en houden rekening met reisafstanden.","jsonQuestion":"Zijn jullie reizen geschikt voor gezinnen?","jsonAnswer":"Absoluut! Wij hebben veel ervaring met het organiseren van familiereizen. We selecteren kindvriendelijke accommodaties en activiteiten en houden rekening met reisafstanden.","images":[]}],"className":"is-style-ga-faq-accordion"} -->
<div class="schema-faq wp-block-yoast-faq-block is-style-ga-faq-accordion"><div class="schema-faq-section" id="faq-question-1776770203629"><strong class="schema-faq-question">Hoe werkt het aanvragen van een offerte?</strong> <p class="schema-faq-answer">Het aanvragen van een offerte is geheel vrijblijvend. Vul het formulier in op onze website of neem telefonisch contact op. Wij nemen binnen 1 werkdag contact met u op om uw wensen te bespreken.</p> </div> <div class="schema-faq-section" id="faq-question-1776770229866"><strong class="schema-faq-question">Is een reis bij GoAfrica altijd maatwerk?</strong> <p class="schema-faq-answer">Ja, wij zijn gespecialiseerd in maatwerk. Hoewel we voorbeeldreizen tonen ter inspiratie, passen we elke reis aan op uw specifieke wensen, budget en reisgezelschap.</p> </div> <div class="schema-faq-section" id="faq-question-1776770249073"><strong class="schema-faq-question">Wat is de beste reistijd voor Afrika?</strong> <p class="schema-faq-answer">Dit verschilt per land en regio. Over het algemeen is Afrika het hele jaar door te bezoeken. Oost-Afrika heeft twee regenseizoenen, terwijl Zuidelijk Afrika seizoenen heeft die tegengesteld zijn aan die van Europa. Wij adviseren u graag per bestemming.</p> </div> <div class="schema-faq-section" id="faq-question-1776770261645"><strong class="schema-faq-question">Zijn jullie reizen geschikt voor gezinnen?</strong> <p class="schema-faq-answer">Absoluut! Wij hebben veel ervaring met het organiseren van familiereizen. We selecteren kindvriendelijke accommodaties en activiteiten en houden rekening met reisafstanden.</p> </div> </div>
<!-- /wp:yoast/faq-block --></div>
<!-- /wp:group -->